pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Bettadelic
title: Bettadelic
description: "We make colorful art of betta fish!"
url: https://bettadelic.art
urlnohttp: bettadelic.art
contact: curator@bettadelic.art
disqus_shortname: bettadelic
enable_subcategories: false

# Social
github: https://github.com/Bettadelic/bettadelic.art
telegram: https://t.me/bettadelic_art
twitter: https://twitter.com/bettadelic
deviantart: https://www.deviantart.com/bettadelic
pixelfed: https://photos.thegayborhood.club/bettadelic
pixelfed_id: bettadelic@photos.thegayborhood.club
webfinger: bettadelic@bettadelic.art

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
 - _jenkinsfile.groovy
 - _ipfs_sync.groovy
