pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: Bettadelic
title: Bettadelic
description: "We make colorful art of betta fish!"
url: https://bettadelic.art
urlnohttp: bettadelic.art
contact: curator@bettadelic.art
disqus_shortname: bettadelic
enable_subcategories: false

# Social
github: https://github.com/Bettadelic/bettadelic.art
telegram: https://t.me/bettadelic_art
twitter: https://twitter.com/bettadelic

# ActivtyPub:
actpub_directory: "activitypub"
actpub_outbox: true
actpub_inbox_url: "https://activitypub.shendrick.net/inboxservice/Inbox/bettadelic"
actpub_profileurl: index.html
actpub_username: bettadelic
actpub_icon: "https://bettadelic.art/static/img/logo.jpg"
actpub_created: "2023-02-01T00:00:00.0000000Z"
actpub_summary: "I post whenever there's a new post on bettadelic.art, the site that randomly generates colorful betta fish!."
actpub_publickeyfile: "activitypub/public.pem"
actpub_following:
 - "https://www.roclongboarding.info/activitypub/profile.json"
 - "https://troop53stories.shendrick.net/activitypub/profile.json"
 - "https://mastodon.sdf.org/users/thenaterhood"
 - "https://tech.lgbt/users/xforever1313"

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - build.cake
 - tools
 - .cake
 - Readme.md
